[Grupo 33] Tela de Jogo (Parcial - Header e questões)
tryber/sd-012-project-trivia-react-redux pull request #210
Opened 2021-08-04 19:49 UTC by thalles-carneiro

2021-08-04 19:57 UTC, VictorDG00 approved these changes

2021-08-04 20:01 UTC, tiagoornelas approved these changes

2021-08-05 09:40 UTC, GMODias requested changes
Parabéns pelo o trabalho!!
Fiz algumas sugestões para simplificar e enxugar o código. Avalia se vale a pena.

2021-08-05 09:40 UTC, GMODias commented on src/components/Question/index.js
> +  shuffleAnswers() {
O código funciona perfeitamente, mas para simplificar a lógica de construção pode ser utilizado algo semelhante abaixo:

  test() {
    const t = [2, 3, 4].map((e, i) => <d.i.v key={ i }> { e } </d.i.v >);
    const a = <d.i.v key='8'>7</d.i.v >; 
    const random = Math.floor(Math.random() * 4);
    console.log(random);
    t.splice(random, 0, a);
    return t;
  }
Nesse caso os elementos já são criados em um array e depois acrescenta o elemento correto em uma posição aleatória.

Vc já pode fazer o map nas respostas erradas com o retorno do array e indices sem fazer o +1 e -1 no índice (pode usar o índice do map direto para passar para a função de criação do elemento) e depois pegar o elemento criado para a resposta correta e colocar no array e devolver para renderizar.

PS.: coloquei <d.i.v> pq quando coloco div normal ele não renderiza o texto

2021-08-05 09:40 UTC, GMODias commented on src/components/Question/index.js
> +
As funções createIncorrectAnswer e createCorrectAnswer são quase iguais.
Acredito que é possível simplificar criando uma só e tratando as diferenças no código.
Vale a pena avaliar.

2021-08-05 09:40 UTC, GMODias commented on src/pages/Trivia.js
> +    if (questions.length !== LENGTH_FIVE) return <Loading />;
Para as perguntas de verdadeiro e falso o tamanho do vetor é 5 também?
Acho que podemos testar e talvez alterar essa lógica para questions.lenght>=2.
Não tenho certeza se o risco existe ou se a solução apresentada vai resolver, mas acredito ser uma avaliação / teste necessária.

2021-08-05 13:07 UTC, thalles-carneiro commented on src/components/Question/index.js
> +
Ótima ideia!
Vou utilizar a mesma lógica de criação dos botões na página de Login :smile:

2021-08-05 13:08 UTC, thalles-carneiro commented on src/pages/Trivia.js
> +    if (questions.length !== LENGTH_FIVE) return <Loading />;
Excelente consideração, mas acredito que o ideal é alterar para `questions.length === 0`. Pois necessitamos que para qualquer valor acima disso o componente `<Question />` seja renderizado. O que acha? :smiley: 

```suggestion
    if (questions.length === 0) return <Loading />;
```

2021-08-05 13:10 UTC, thalles-carneiro commented on src/components/Question/index.js
> +  shuffleAnswers() {
Acredito que entendi a sua sugestão, tentei implementar aqui e até funcionou, mas voltou um problema anterior, que ao clicar no botão, as respostas trocavam de lugar na tela :confused:

Podemos ver juntos na reunião de hoje se achamos uma solução para isso :+1:

2021-08-05 14:51 UTC, GMODias commented on src/components/Question/index.js
> +  shuffleAnswers() {
Acho que entendi o que vc falou... todas as respostas mudam de posição ou só a correta?
se for só a correta, a saída é salvar o random position dela no state. Ele começa com null, e se for null dentro da função ele calcula uma nova posição, senão ele pega a que já está setada.

2021-08-05 14:55 UTC, GMODias reviewed
Avalia a sugestão que eu dei para a questão de mudança de ordem por favor, e verifica se faz sentido.

2021-08-05 14:55 UTC, GMODias commented on src/pages/Trivia.js
> +    if (questions.length !== LENGTH_FIVE) return <Loading />;
Concordo, a lógica fica até mais simples. Boa!!

2021-08-05 15:09 UTC, thalles-carneiro commented on src/components/Question/index.js
> +  shuffleAnswers() {
Todas elas acabam mudando :confused: 

Porque ao criar de uma vez os botões de cada resposta e logo após embaralhar, utilizamos essa função para retornar o array pronto e colocamos no render não é?

Dessa forma, ao atualizarmos as props que recebemos e modificamos o `answered`, o componente renderiza novamente e a função que cria e já embaralha as respostas irá executar novamente, embaralhando as respostas.

Justamente pra tentar mitigar isso, que eu e o Tiago chegamos a conclusão que o melhor seria salvar as respostas embaralhadas, e usar esse array fixo para criar cada botão.

2021-08-06 17:07 UTC, GMODias approved these changes

2021-08-06 17:08 UTC, merged