[Group 23] [Bernardo] Requisito 3
tryber/sd-012-project-trivia-react-redux pull request #271
Opened 2021-08-04 22:50 UTC by Bernardo-Coelho-Cezario

2021-08-04 23:03 UTC, rslfilho requested changes
Apenas uma mudança rápida

2021-08-04 23:03 UTC, rslfilho commented on src/pages/Login.js
> +          <Link to="settings">
precisa da / antes do settings, não? "/settings"

2021-08-05 18:55 UTC, Bernardo-Coelho-Cezario commented on src/pages/Login.js
> +          <Link to="settings">
Precisa não, no App.js que esta redirecionando pra pagina /settings, ai só especifica o local do link. Ou estou errado? Porque a pagina do quiz (<Link /> de cima) eu também coloquei sem o barra, ai se der problema assim eu teria que alterar ele também, aguardo resposta

2021-08-05 18:59 UTC, rslfilho commented on src/pages/Login.js
> +          <Link to="settings">
Tu chegou a testar na aplicação rodando? Eu sempre usei o to com a barra, e na documentação os exemplos são com barra também

2021-08-05 19:02 UTC, Bernardo-Coelho-Cezario commented on src/pages/Login.js
> +          <Link to="settings">
No que eu testei, tava mandando pro endereço certo, mas vou mudar de precaução então

2021-08-05 19:05 UTC, rslfilho approved these changes

2021-08-05 19:21 UTC, CaioMorato approved these changes
Show

2021-08-05 19:22 UTC, merged